name: Build Godot (branch 66) + GGML (experimental)

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build_reusable.yml
    with:
      godot_ref: "66"
      build_name: "public_ggml"
      include_ggml: true
    secrets: inherit
