name: 🏗️🔥 Build Godot (branch 66+hot)

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build_reusable.yml
    with:
      godot_ref: "66+hot"
      build_name: "public_ggml+hot"
    secrets: inherit
